### ISSUE TITLE
im so happy for this

### ISSUE THREAD

**Issue by Gabiworld** [Juansecu/OpenToonix-RTMP-Server#1]
i'll play this when this go out all days litterally, also you think that after u finish the 3.0 mundo toonix version, u could make a version in html5? they did that with club penguin and mundo toonix is simplier

**Comment by Juansecu** [comment]
Hi @Gabiworld.

Actually, it's a possibility, but not for sure. Of course, we would need some help from experienced people with HTML5 for making this real.

By the way, don't hesitate to join us on [Discord](https://discord.gg/8ZWkyXnv4h).

**Comment by Gabiworld** [comment]
can u delete this issue is kinda unnecessary
